---
- name: Configure Ansible controller
  hosts: lab-controller
  tasks:
  - name:  Install Ansible Update
    become: yes
    ansible.builtin.package:
      name: ansible
      state: latest

# - name: Install roles
#   hosts: lab-hosts
#   vars:
#     ansible_become: true
#   roles:
#   - role: ansible-hardening
#     vars:
#       stig_version: rhel7
#       security_enable_pwquality_password_set: yes
#       security_password_max_lifetime_days: 90


- name: Configure DNS server
  hosts: ansible-lab-host1
  vars:
    ansible_become: true
  tasks:  

  - name: Install dnsmasq
    ansible.builtin.package:
      name: dnsmasq
      state: latest

  - name: Set local Hostname
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.4'
      line: '10.1.2.4 {{ ansible_hostname }}'

  - name: Disable DNS service
    ansible.builtin.service:
      name: systemd-resolved
      enabled: no
      state: stopped

  - name: Set dnsmasq config file
    ansible.builtin.copy:
      src: files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: '0644'

  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      enabled: yes
      state: restarted



      