---
- name: Configure Ansible controller
  hosts: lab-controller
  tasks:
  - name:  Install Ansible Update
    become: yes
    ansible.builtin.package:
      name: ansible
      state: latest

# - name: Install roles
#   hosts: lab-hosts
#   vars:
#     ansible_become: true
#   roles:
#   - role: ansible-hardening
#     vars:
#       stig_version: rhel7
#       security_enable_pwquality_password_set: yes
#       security_password_max_lifetime_days: 90


- name: Configure DNS server
  hosts: ansible-lab-host1
  vars:
    ansible_become: true
  tasks:  
  - name: Install dnsmasq
    ansible.builtin.package:
      name: dnsmasq
      state: latest
  - name: Set local Hostname
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.4'
      line: '10.1.2.4 {{ ansible_hostname }}'
  - name: Add Host2
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.5'
      line: '10.1.2.5 ansible-lab-host2'
  - name: Add Host3
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.6'
      line: '10.1.2.6 ansible-lab-host3'
  - name: Add Controller
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.1\.4'
      line: '10.1.1.4 ansible-lab-controller'
  - name: Disable DNS service
    ansible.builtin.service:
      name: systemd-resolved
      enabled: no
      state: stopped
    notify: Restart dnsmasq
  - name: Set dnsmasq config file
    ansible.builtin.copy:
      src: files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: '0644'
  - name: Add upstream servers
    ansible.builtin.copy:
      src: files/resolv.dnsmasq.conf
      dest: /etc/resolv.dnsmasq.conf
      owner: root
      group: root
      mode: '0644'

- name: Configure hosts to use local DNS
  hosts: 
  - ansible-lab-controller
  - ansible-lab-host2
  - ansible-lab-host3
  vars:
    ansible_become: true
  tasks:
  - name: Set resolv.conf nameserver
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: 'nameserver 10.1.2.4'  

  handlers:
  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      enabled: yes
      state: restarted
    
- name: Configure Samba Server
  hosts: ansible-lab-host2
  vars:
    ansible_become: true
  roles:
  - bertvv.samba

- name: Configure Samba Client
  hosts: ansible-lab-host3
  vars:
    ansible_become: true
  tasks:
  - name: Install client deps
    package:
      name: cifs-utils
      state: latest
  - name: Create Credential File
    template:
      src: .files/.smbpassword
      dest: /home/{{ admin_un}}/.smbpassword
      owner: '{{ admin_un }}'
      group: '{{ admin_un }}'
      mode: '0600'
  - name: Add share mount
    mount:
      src: //10.1.2.5/MDHTtestshare
      path: /mnt/smbshare
      fstype: cifs
      opts: credentials=/home/{{ admin_un }}/.smbpassword
      state: mounted
  - name: Set mount as writeable
    file:
      path: /mnt/smbshare
      state: directory
      mode: '0777'
